CFLAGS= -DHAVE_CONFIG_H -DBUILD_UI_ONLY -Wall -g -fsingle-precision-constant
CXXFLAGS = $(CFLAGS) -fno-exceptions -fno-rtti -DTIXML_USE_STL
ASFLAGS = $(CFLAGS) -c
OBJS=UI.o

LIBS=-lSDL -lSDL_image -lSDL_ttf

ctorrent.bin: $(OBJS)
	g++ -o ctorrent.bin $(CXXFLAGS) $(OBJS) $(LIBS)

clean:
	rm -f $(OBJS) ctorrent.bin
